---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-configsvr
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: configsvr
    helm.sh/chart: {{ include "mongodb.chart" . }}
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: configsvr
  ports:
    - name: mongodb
      port: 27019
