apiVersion: v2
name: gangway
version: 1.1.0
description: An application that can be used to easily enable authentication flows via OIDC for a kubernetes cluster.
type: application
home: https://github.com/heptiolabs/gangway
keywords:
  - authentication
  - k8s
  - oidc
maintainers:
  - name: gabibbo97
    email: gabibbo97@gmail.com
appVersion: v3.2.0
