apiVersion: v1
appVersion: "6.0.1"
description: Keycloak gatekeeper
name: keycloak-gatekeeper
home: https://github.com/keycloak/keycloak-gatekeeper
icon: https://raw.githubusercontent.com/keycloak/keycloak-misc/master/logo/keycloak_logo_600px.png
keywords:
  - authentication
  - authorization
  - keycloak
  - proxy
version: 1.3.0
engine: gotpl
maintainers:
  - name: gabibbo97
    email: gabibbo97@gmail.com
